### ISSUE TITLE
Can't resolve './loaders/neshan_map_loader' in react

### ISSUE THREAD

**Issue by mohammadrezaataeii** [NeshanMaps/react-neshan-map-leaflet#12]
after install package and import in my component i got the error
this is full error message : 
ERROR in ./node_modules/react-neshan-map-leaflet/dist/NeshanMap.js 2:0-60
Module not found: Error: Can't resolve './loaders/neshan_map_loader' in 'C:\Users\Desktop\time-line\node_modules\react-neshan-map-leaflet\dist'
Did you mean 'neshan_map_loader.js'?
BREAKING CHANGE: The request './loaders/neshan_map_loader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by MomoTaheri** [comment]
سلام

یه بار پوشه node_modeules رو بصورت دستی پاک کنید و بعدش دوباره تو ترمینال دستور npm i رو بزنید شاید حل بشه
