### ISSUE TITLE
error in next js

### ISSUE THREAD

**Issue by hossein-ghanbari** [NeshanMaps/react-neshan-map-leaflet#4]
I encounter this error when using Next js

Error: Cannot find module 'E:\appName\node_modules\react-neshan-map-leaflet\dist\loaders\neshan_map_loader'
imported from E:\appName\node_modules\react-neshan-map-leaflet\dist\NeshanMap.js

**Comment by electromidz** [comment]
Hi @hossein-ghanbari  you can use older version in NPM package 
https://www.npmjs.com/package/react-neshan-map-leaflet
version 1.0.3 myabe work with you I guess

**Comment by hossein-ghanbari** [comment]
@electromidz 
Thanks for your guidance .
I used the dynamic import of next js and my problem was solved

**Comment by loveyandex** [comment]
how to import

**Comment by hossein-ghanbari** [comment]
> how to import

const Map = dynamic(() => import("react-neshan-map-leaflet/dist/NeshanMap"), {
	ssr: false
});
